### ISSUE TITLE
How to left align labels?

### ISSUE THREAD

**Issue by phylor** [Ezelia/EZGUI#10]
First of all, thanks for the effort with the library, it really looks promising!

I'm trying to align labels vertically. Their text should be left aligned (i.e., the first letter of every label should have the same x coordinate).

However, the labels' text is currently centered. On the todo list of the repo's readme you list the text alignment, so I guess it's not possible to left align the text within a label.

Is there another way to have labels aligned vertically, so that the text is left aligned?

By the way, the documentation is (understandably) quite sparse. Can we help in any way improving it?

**Comment by alaa-eddine** [comment]
Hi @phylor , there is unfortunately no complete support for text alignment, I started working on but the way PIXI handles native fonts and bitmap fonts is different, making the alignment behaves differently.

if you are using native fonts, you can use anchor setting to align the text. in your case you should add  the following setting to the label settings

```
anchor : {x:0, y:0.5},
```

here is an example settings for a label aligned to the left

``` javascript
                {
                    id: 'label1',
                    text: 'Text here',
                    font: {
                        size: '35px',
                        family: 'Arial'
                    },
                    anchor: { x: 0, y: 0.5 },
                    component: 'Label',
                    position: 'center',
                    width: 600,
                    height: 80
                },
```

as you noticed it's on my Todo list, but still didn't find time to implement it.

for documentation,  I started a wiki here https://github.com/Ezelia/EZGUI/wiki but it's far from being complete. I also try to make an example of every feature with commented code but I'm aware it's not enought !
so any help is welcome  : wiki additions, tutorials, code examples ...etc :)
