### ISSUE TITLE
Does not work with Phaser 2.4 ?

### ISSUE THREAD

**Issue by MaksJS** [Ezelia/EZGUI#11]
I'm trying to make it work with the dev branch of Phaser, but I have a 'baseTexture not defined' error because PIXI.TextureCache is empty

**Comment by alaa-eddine** [comment]
I didn't tested EZGUI with Phaser dev branch yet, but if the error comes from PIXI.TextureCache missing, make sure you are using the right version of PIXI because in Pixi v3.x Pixi.TextureCache has been moved to Pixi.utils.TextureCache.
Phaser 2.x is not compatible with Pixi v3.x, it should use Pixi v2.x

**Comment by MaksJS** [comment]
Hi @alaa-eddine, I'm using Pixi v2.x, maybe you should have a look at this part of Phaser 2.4's changelog : 

> Frame.uuid has been removed (was flagged as deprecated for several releases). This has a two-fold effect: First it means that the property no longer exists and secondly it means that the AnimationParser (the class responsible for loading sprite sheets and texture atlases) no longer has to call either RandomDataGenerator.uuid OR populates the PIXI.TextureCache. The first saves some CPU time and the second saves memory by not creating references to textures it doesn't ever use. The PIXI.TextureCache is now ignored by Phaser other than for the __missing and __default textures.

**Comment by alaa-eddine** [comment]
humm this will break things in EZGUI.
I need to know where the textures are cached then, or find a way to force cache.
I'm also thinking of a whole refactor of EZGUI because it still relies a lot on Pixi structure, and the next major phaser version (3.x) will not use Pixi...

**Comment by alaa-eddine** [comment]
I managed to workaround the TextureCache issue but it seems that Phaser 2.4 has another breaking change : it don't use the default tilingTexture and EZGUI need it !
So I think that the fix will take some time...

**Comment by weilitao** [comment]
When Phaser 2.4 compatible version would be available?

**Comment by alaa-eddine** [comment]
I took a look at Phaser 2.4 changes and unfortunately it have many breaking changes.
Phaser 2.4 removed many core Pixi classes and functions on which EZGUI depend (Texturecache, Sprite, tilingSprite ...etc) .
this make core EZGUI incompatible with Phaser 2.4.
it was known that Phaser 3 will have such breaking changes but I thought that all 2.x version will share Pixi core features .... and I was planing to release EZGUI v1 with Phaser/Pixi support relying on shared features then release EZGUI v2 with complete refactor and support for multiple engines. but this plan will not work now :(

I think that the best solution now is to rebuild EZGUI from scratch with multiple engines support in mind.... the down side is that it'll take some time.
I'm also thinking to rewrite it in vanilla JS to make 3rd party contributions easier (I personaly prefer Typescript but it's not the case of everyone) .

If I find a way to write a workaround/polyfill to bring phaser 2.4 support I'll do it of course, but from my first look at the code it'll not be simple :/

**Comment by weilitao** [comment]
Sound sadly :( Hope EZGUI can support Phaser 2.4 soon. BTW, I think to rewrite it in Typescript is acceptable. So many famous JS library being rewritten with Typescript ( like Angular 2, Ionic 2, dojo2 ), so the future would be ES6/ES7/Typescript :)

**Comment by alaa-eddine** [comment]
I'm exploring the possibility to reintegrate what phaser 2.4 removed in a separate compatibility package, but it's not simple since I don't know phaser very well.

I hope I can come up with a workaround soon.... it'll give me some time to rewrite EZGUI from scratch in a cleaner way.

**Comment by alaa-eddine** [comment]
Hi @weilitao , @MaksJS !

just pushed a new version with phaser 2.4 compatibility :)

this version is only available in git repo.
please note that you need to include phaser-compat-2.4.js script _after_ your phaser.js (see https://github.com/Ezelia/EZGUI/blob/master/examples/Phaser/phaser-2.4.html)

and if you use phaser loader to load specific resources for your gui you need to add a special onLoadComplete event listener, see https://github.com/Ezelia/EZGUI/blob/master/examples/game/phaser-2.4.html around line 193

it's still better to load all graphic resources using a theme file, so you keep your gui stuff and game stuff separated.

in a next version I'll try to remove the need of event listener trick, and hopefully the compatibility script.

Let me know if it's working for you

**Comment by budda** [comment]
The phaser-compat-2.4.js solved my head scratching straight away. Thanks for the temporary fix Alaa!

**Comment by alaa-eddine** [comment]
nice :) 
don't forget the onLoadComplete listener if you load any theme resource with phaser loader.

I'll mark this issue as solved for now.

**Comment by weilitao** [comment]
It works like a charm, Thanks Alla! I'll do more compatible test later.

**Comment by scabros** [comment]
hi, i really would like to thank you for this great piece of software. 
i think it does not work again with phaser 2.4.4 i receive a "TypeError: game is undefined" in phaser-2.4.4.js line 20082:

PIXI.CanvasRenderer = function (game) {
[snip]
    this.resolution = game.resolution;

the callstack shows that this is called from compatibility.ts:107 (althought that file doesn't fisically exists). 

after that error, i receive "TypeError: EZGUI.Theme is undefined" in my app.js when calling EZGUI.Theme.load(...);

i am already loading phaser-compat-2.4.js script after phaser-2.4.4.js

can you give me some hint about this?

thanks in advance!

**Comment by scabros** [comment]
sorry, the callstack from the "game is undefined" error comes from: 

EZGUI.js line 652:

EZGUI.tilingRenderer = new PIXI.CanvasRenderer();

PIXI.CanvasRenderer in phaser receives game as parameter...

**Comment by scabros** [comment]
hi, another update:
i found a workaround, i commented lines in EZGUI.js from 644 to 714, and copied those lines to a custom function "enableEZ". then i call enableEZ in the create method. the only difference in the lines is that 
EZGUI.tilingRenderer = new PIXI.CanvasRenderer(); 
now is:
EZGUI.tilingRenderer = new PIXI.CanvasRenderer(game);

and this works. the renderer must be in Phaser.CANVAS (tested in firefox on linux).

**Comment by alaa-eddine** [comment]
Hi @scabros,
Thank you for reporting this issue, actually, Phaser 2.4.4 has introduced some new breaking changes.
I'll look at them in the next few days and publish an update.

in the meantime, you can continue using your workaround if it fixes the issue for you :)

**Comment by scabros** [comment]
hi @alaa-eddine , thanks for your response.
yes, the workaround works great. 
anyway, i encourage you to keep working on this, it is, IMHO, the best GUI lib available to phaser.
if i had the required knowledge i would cooperate with you to improve this.

**Comment by alaa-eddine** [comment]
Just pushed a new version with a partial fix.
this fix works fine with Canvas Renderer but webGL renderer seem to have an issue.
this seems to be related to phaser code but I need to isolate it in a separate example so I can open an issue on phaser repository.

**Comment by alaa-eddine** [comment]
Update : the issue with WebGL renderer is due to a phaser issue which was fixed here : https://github.com/photonstorm/phaser/issues/2141

since the patch is still not available in official branch here is a patched version http://ezgui.ezelia.com/js/phaser-2.4.4.js
