### ISSUE TITLE
How to swallow event of button?

### ISSUE THREAD

**Issue by fallenleavesguy** [Ezelia/EZGUI#15]
I used game.input to get user input in phaser,but click event of ezgui will  propagate to phaser input,how can I swallow button click event,I don't want phaser get my click event on button.Thank you.

**Comment by alaa-eddine** [comment]
the original event is stored in PIXI event so you can use stopPropagation there.

here is an example 

``` javascript
EZGUI.components.MyButton.on('mousedown', function (event) {
    event.data.originalEvent.stopPropagation();
});
```

**Comment by fallenleavesguy** [comment]
I have a look at property of event parameter,It's a Phaser.Pointer,so this example can't work on phaser.

**Comment by yeluoqiuzhi** [comment]
if I can get dom event from this pointer,I can use stopPropagation(),but I don't know how to get dom event from Phaser.Pointer

**Comment by fallenleavesguy** [comment]
I want to do that,any pointer of phaser can't get clicked event,when I clicked ezgui Button.
some code like this:

``` javascript
 game.input.onUp.add(function(pointer){
            console.log(pointer);
});
```

I don't want phaser dispatch the onUp signal,when I click ezgui Button.
How could I do that?

**Comment by alaa-eddine** [comment]
this seem to be more related to phaser than EZGUI, I don't know how to stop event propagation in phaser, but one solution is to pass some boolean to the pointer and check if that boolean is set.
in EZGUI event, set pointer.stopPropagation to true.
in Phaser event, if pointer.stopPropagation == true then set it to false and exit, if it's unset or false then execute your phaser code.

there is maybe a cleaner way to do it, but I don't know Phaser event system a lot.

**Comment by fallenleavesguy** [comment]
Thank you very much! I know this solution,but I think It isn't beaultiful.I'll consider this solution.

**Comment by alaa-eddine** [comment]
I tried to debug a phaser example and it apear that Phaser hides the original dom event, if so there is no way to stop the propagation using native JS stopPropagation() function.
there's maybe a phaser way to do it. or to get access to the original DOM event. 

I'm thinking to write a specific event manager for EZGUI instead of relying on Phaser/Pixi events systems but this is lot of work and may generate conflicts with those libraries :/

**Comment by fallenleavesguy** [comment]
writing a specific event manager is a good job.Thanks for your job.
