### ISSUE TITLE
Rendering GUI on a layer for a HUD

### ISSUE THREAD

**Issue by budda** [Ezelia/EZGUI#16]
Is it possible to render then EZGUI as a group layer on top of the game view port to provide controls around the edge of the screen?

Using something like game.add.group();

**Comment by alaa-eddine** [comment]
I guess you are using phaser.

each EZGUI component is actually a child of a phaser container, and this container is accessible from the component.

for example if you define a window called MyWin with two buttons : btn1 and btn2

then you can access the phaser containers through
EZGUI.components.MyWin.phasergroup
EZGUI.components.btn1.phasergroup
EZGUI.components.btn2.phasergroup

EZGUI.components.MyWin.phasergroup is actually a phaser container containing EZGUI.components.MyWin component.

you can use it to rearrange your GUI on top or on bottom of your game.
