### ISSUE TITLE
Programmatically adding child components to a List seems to stack them in the corner

### ISSUE THREAD

**Issue by budda** [Ezelia/EZGUI#17]
Based on your 'app' example I changed the population of the 'List' component child items from static to dynamic based on the result of a json array.

After some guess work it looks like the working way to add child items is:

```
EZGUI.components.thumbnails.addChild(thumbnail);
```

Where 'thumbnails' is the 'id' set on the 'list' component.

However, unlike when defining a load of child 'text' components which get laid out in rows and columns, my above code just seems to stack them in the top left corner of the 'list' component.

Once i've finished looping through my array of items should I call something to re-layout the EZGUI 'list' component ?

**Comment by alaa-eddine** [comment]
addChild in List component is buggy because it conflict with the original Pixi addChild method, and I still didn't found a clean way to use it while keeping compatibility.

This is why I recommend adding the children dynamically to the gui definition before creating the gui element when it's possible.

in your case, try using EZGUI.components.thumbnails.addChildAt(thumbnail, 1)  which work better (but also have some issues)

**Comment by budda** [comment]
Tried EZGUI.components.thumbnails.addChildAt(thumbnail, 1) but it didn't appear to make any difference.

All the items are rendered in the top left corner on top of each other still.

Adding the items before the GUI is rendered is not possible as the user interacts with the UI first to execute a search and then I want to insert the search results as children to the list component.

**Comment by alaa-eddine** [comment]
I see now what you are trying to do.
this is one of the next enhancements I'm trying to add : live update layouts ...

in your case you have two options : 
1 - Using addChild/addChildAt then reposition the children using code (you can change the position.x and position.y of each children at runtime).
in this case, the children **are not** accessible under EZGUI.components.thumbnails (those are PIXI children), your children items are _**available in EZGUI.components.thumbnails.container.children**_ ; you can loop and update positions as you like.

2 - Create a template json Layout and fill it with children after each search, then destroy the old container and create a new one from the updated layout.

**Comment by alaa-eddine** [comment]
(Not directly related to your issue, but can help you a lot.)

I just pushed a new version with percentages positionning support.
the percentages values are only acceptable in children elements.

you can set width and height and positions to percentage values like this : 

```
height:'50%',
width: '25%',
position: {x:'10%', y:0}
```

the percentage values are relative to parent width and height.

**Comment by alaa-eddine** [comment]
Had some spare time this week end :) 
here is a new update now you can use AddChild / AddChildAt to add childrens to Lists programmatically, they will be correctly positioned.

there's still one limitation, if you use bindchildren() to bind events to your list's children, programmatically added children will not be bound automatically, it's hard to determine if the developer want to have the same action for newly added items or not so it's up to the developer to decide.

hope it'll help

**Comment by budda** [comment]
Thanks for pursuing this. I've updated the EZGUI.js library and re-ran my code that's adding the the child items.

```
      var thumbnailCfg = JSON.parse(JSON.stringify({ text: 'item', component: 'Button', position: 'center', width: 100, height: 100 }));

      this.searchResults.forEach(function(currentValue, index, array) {
        console.log(currentValue);

        var thumbnail = EZGUI.create(thumbnailCfg, 'kenney');
        thumbnail.id = 'pic' + index;
        thumbnail.text = 'Pic ' + index;
        EZGUI.components.thumbnails.addChild(thumbnail,1);
      });
```

It gives some odd layout positions which i can't see a reason for. I was expecting the same child item grid layout as if i'd listed al the child items at creation time? e.g

```
component: 'List',
layout: [4, 3],
children: [
             { text: 'item', component: 'Button', position: 'center', width: 100, height: 100 },
             { text: 'item', component: 'Button', position: 'center', width: 100, height: 100 },
]
```

Screenshot follows:
![screen shot 2015-09-20 at 22 21 34](https://cloud.githubusercontent.com/assets/104929/9982978/feff2ce4-5fe5-11e5-8d58-cc02ff987149.jpg)

**Comment by alaa-eddine** [comment]
not sure if it make difference, but you are calling addChild with additional parameter 

try 

```
EZGUI.components.thumbnails.addChild(thumbnail);   //without 1 as second parameter
```

otherwise use addChildAt giving the index of your item, in your case it'll be something like

```
EZGUI.components.thumbnails.addChildAt(thumbnail,index);  // the child position calculation is based on index value
```

**Comment by budda** [comment]
Sorted it after seeing you added an example of this too!
Fixed version

```
      var thumbnailTpl = { text: 'item', component: 'Button', position: 'left', width: 100, height: 100 };
      var thumbnail = false;

      this.searchResults.forEach(function(currentValue, index, array) {
        console.log(currentValue);

        thumbnailCfg = JSON.parse(JSON.stringify(thumbnailTpl));
        thumbnailCfg.id = 'pic' + index;
        thumbnailCfg.text = 'Pic ' + index;

        EZGUI.components.thumbnails.addChild(EZGUI.create(thumbnailCfg, 'kenney'));
      });
```

Moving the thumbnailCfg and stringify into the loop seemed to be the fix.

I did try without the '1' you mentioned and it made no difference.

Cheers for the quick response though!

**Comment by alaa-eddine** [comment]
oh yes I understand what hapened now.
you was using the same layout to create multiple children, since the layout is used internally you was overriding the configuration of a child with another ...

good to see it working for you now :)

**Comment by nickschot** [comment]
```
there's still one limitation, if you use bindchildren() to bind events to your list's children, programmatically added children will not be bound automatically, it's hard to determine if the developer want to have the same action for newly added items or not so it's up to the developer to decide.
```

I'm having a related problem with this. Adding stuff with addChild and addChildAt works fine, but I can't seem to get click events working. After adding the elements I'm calling:

```
EZGUI.components.my0Button.on('click', function(event, me) {
        console.log('Does this work?');
    });
```

I've tried playing with the Z-index, but nothing seems to work. When the stuff is loaded at first everything works fine.

EDIT: temporarily solved it by editing the template and destroying/recreating the specific GUI component every time the list has changed.
