### ISSUE TITLE
DisplayObjectContainer is deprectated

### ISSUE THREAD

**Issue by darkoverlordofdata** [Ezelia/EZGUI#23]
I'm getting a compiler error from tsc against the latest version of PIXI (3.07):

Error (141, 37) TS2305 Module 'PIXI' has no exported member 'DisplayObjectContainer'.

I'm using the typescript defs from https://github.com/pixijs/pixi-typescript.
If I use the ones provided with EZGUI,then  I get a slew of other errors:

Error:(8, 27) TS2305: Module 'PIXI' has no exported member 'Container'.
Error:(10, 32) TS2305: Module 'PIXI' has no exported member 'SystemRenderer'.
Error:(6, 28) TS2305: Module 'PIXI' has no exported member 'extras'.
Error:(23, 28) TS2305: Module 'PIXI' has no exported member 'filters'.
Error:(38, 12) TS2339: Property 'loader' does not exist on type 'typeof PIXI'.
Error:(81, 70) TS2339: Property 'RENDERER_TYPE' does not exist on type 'typeof PIXI'.

**Comment by darkoverlordofdata** [comment]
So, I figured out that I can edit EZGUI.d.ts, and change all PIXI.DisplayObjectContainer references to PIXI.Container, and then my project will compile.

**Comment by alaa-eddine** [comment]
Hi @darkoverlordofdata, please note that the d.ts file is mainly used to get intellisense working correctly, you can just exclude it from the project while compiling.

The errors you got are due to some manual modification I made to the d.ts because EZGUI is compatible with both PIXI 2.x and PIXI 3.x and there was some deprecations between versions 2.x and 3.x .... there is a compatibility layer to handle this.

if I make EZGUI code compatible with official Pixi 3 .d.ts it'll break the 2.x compatibility and vice-versa.

I don't have a clean way to have both .d.ts supported while keeping compatibiliy.

again the d.ts files are only used here for intellisense, you can exclude them from the project to avoid such error.

In next versions I'll switch to gulp build system which give more control over compilation.

**Comment by darkoverlordofdata** [comment]
I love code completion, however my main reason for using typescript is that
the compile time type checking saves my sanity (maybe...). And since my
project is written in typescript, I actually do have to compile it :)
But I do have an acceptable workaround - you can see it in action if you
like:

https://darkoverlordofdata.com/spaceship-warrior-ts/
https://github.com/darkoverlordofdata/spaceship-warrior-ts/tree/alternate

Thanks,
Bruce

On Thu, Oct 1, 2015 at 2:24 AM, Alaa-eddine K. notifications@github.com
wrote:

> Hi @darkoverlordofdata https://github.com/darkoverlordofdata, please
> note that the d.ts file is mainly used to get intellisense working
> correctly, you can just exclude it from the project while compiling.
> 
> The errors you got are due to some manual modification I made to the d.ts
> because EZGUI is compatible with both PIXI 2.x and PIXI 3.x and there was
> some deprecations between versions 2.x and 3.x .... there is a
> compatibility layer to handle this.
> 
> if I make EZGUI code compatible with official Pixi 3 .d.ts it'll break the
> 2.x compatibility and vice-versa.
> 
> I don't have a clean way to have both .d.ts supported while keeping
> compatibiliy.
> 
> again the d.ts files are only used here for intellisense, you can exclude
> them from the project to avoid such error.
> 
> In next versions I'll switch to gulp build system which give more control
> over compilation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ezelia/EZGUI/issues/23#issuecomment-144668142.

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by alaa-eddine** [comment]
I agree, code completion is a must nowdays 
When I suggestion to exclude the .d.ts it was for the compile time only, but your solution is actually better :)

btw : I'll feature games using EZGUI on the EZGUI official page in the next update, I'll add your game ;)

I'm working right now on tabs component, when I'm finished I'll update the repo and the official page.

**Comment by darkoverlordofdata** [comment]
Thanks - this project started out as a bet to see if I could port the java
version of artemis-framework to typescript. It's really exceeded my
expectations.

On Thu, Oct 1, 2015 at 10:54 AM, Alaa-eddine K. notifications@github.com
wrote:

> I agree, code completion is a must nowdays
> When I suggestion to exclude the .d.ts it was for the compile time only,
> but your solution is actually better :)
> 
> btw : I'll feature games using EZGUI on the EZGUI official page in the
> next update, I'll add your game ;)
> 
> I'm working right now on tabs component, when I'm finished I'll update the
> repo and the official page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Ezelia/EZGUI/issues/23#issuecomment-144800383.

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by alaa-eddine** [comment]
interesting :)
We also use an entity component system engine internally and will release it soon to the public .
it's different from artemis-framework logic, but I also believe that ECS paradigm fits very well in game development, not only for multiplayer implementation.
