### ISSUE TITLE
Is it possible to use shadow or transparent images for components ?

### ISSUE THREAD

**Issue by besartberisha** [Ezelia/EZGUI#24]
Hello, I was wondering if I can add shadow effect to components (e.g window), I tried using transparent images but when it renders it shows white background at the transparent part.

![demo](https://cloud.githubusercontent.com/assets/7255779/10639494/eb882614-7810-11e5-80b2-38307e54e729.jpg)

**Comment by alaa-eddine** [comment]
The transparency is supported, I think that the issue here comes from your image format.

Are you sure you are using PNG format and that you saved it **with transparency** support (alpha channel) ?

can you share one of the images you used for corners or lines ?

**Comment by besartberisha** [comment]
Yes the images are PNG with transparency 
This is one of the images used with shadow
![window-b-l](https://cloud.githubusercontent.com/assets/7255779/10658241/3f5c522c-7895-11e5-8a49-e1caf93ac0c3.png)

But when i remove shadow from element it works just fine. 
![window-b-l](https://cloud.githubusercontent.com/assets/7255779/10658236/2cf4edb0-7895-11e5-8840-9b6072ee0151.png)

At first I thought it was the shadow that included white background but tested as image on an HTML file with a background-color and the transparency works.

Image with css background-color:

![demo](https://cloud.githubusercontent.com/assets/7255779/10658351/42a3ae2a-7896-11e5-8e00-e150dc125c00.png)

**Comment by alaa-eddine** [comment]
This is wired, actually EZGUI do not render the images, the rendering use PIXI or Phaser.
The fact that the transparency work when you remove the shadow let me think that there is some issue with the image format, maybe there is an incompatibility issue between the image format you are using and PIXI ...

Are you using Pixi or Phaser, which version ?

if you create a sprite using your image (with Pixi or phaser depending on your game), do you get transparency ?

Have you tried to save your image with different PNG settings ? (different depth, different compression algorithm ....etc)

**Comment by besartberisha** [comment]
Sorry I didn't see that you replied :/

I am using pixi v3, and used the TexturePackerGUI to generate sprite images, on sprite images you can actually see the transparency.
I also tried saving PNG different but same result, the moment I remove shadow from element it works otherwise it shows the white background.

Anyways I'm using images without shadow for now.

Thanks for  your help and quick responses.

**Comment by alaa-eddine** [comment]
no problem, I tried with similar image (added a shadow) and it worked just fine.

if you can attach the images you are using, I'll try to make a test when I have some spare time :)
