### ISSUE TITLE
Clicking effect is not showing on Blue buttons

### ISSUE THREAD

**Issue by todorgrigorov** [Ezelia/EZGUI#26]
I am using the built-in Kenney theme with the default blue buttons, but once I click the element, the bottom part is not "animated" properly, as shown in the examples. Is this a common bug or am I doing something wrong?

**Comment by alaa-eddine** [comment]
Hello,
Can you explain more what do you mean by not animated properly ?
do you have a live example I can check ?

**Comment by todorgrigorov** [comment]
I've found the solution.
The "kenney" atlas json file was wrong and the "down" assets were not the proper ones but now everything is fine.
Have a nice day!

**Comment by alaa-eddine** [comment]
Good news 
if you publish a game or an application using EZGUI let me know, I'll feature it on ezgui website :)
