### ISSUE TITLE
Multi-line text in label

### ISSUE THREAD

**Issue by phylor** [Ezelia/EZGUI#28]
I'm trying to enable word wrap in a label. There's no example for it as far as I can tell. However, there are a couple of keywords in the source, so I assume that it's supported :)

I tried:

```
{
  id: 'myLabel',
  component: 'label',
  text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consequat purus pulvinar libero maximus suscipit vel vel ligula. Quisque id ante nulla. Phasellus ac urna nec eros hendrerit ullamcorper sed ac urna. Integer facilisis blandit enim ut dapibus. Vestibulum mattis ipsum at fermentum bibendum. Fusce semper dictum arcu, sed placerat erat accumsan sed. Aliquam nec turpis et neque euismod rhoncus et ut nulla.',
  wordWrap: true,
  wordWrapWidth: 150,
  width: 200,
  height: 100
}
```

However, the text is not wrapped. Including a `\n` for an explicit line break works fine.

I also tried to put `wordWrap` and `wordWrapWidth` in a `style` object, but still no effect.

Is word wrap supported? If so, could you please provide a simple example? Thanks in advance!

**Comment by alaa-eddine** [comment]
Hi,
wordWrap and wordWrapWidth are the right options but you should use them under font settings.
your settings should look like 

```
 {
  id: 'myLabel',
  component: 'label',
  text: '...',
    font: {
        size: '35px',
        family: 'Arial',
        wordWrap: true,
        wordWrapWidth: 150  
    },  

  width: 200,
  height: 100
}
```

**Comment by phylor** [comment]
Works perfectly, thank you!
