### ISSUE TITLE
is this work with electron ?

### ISSUE THREAD

**Issue by ghost** [Ezelia/EZGUI#29]
i try to use EZGUI in my phaser on electron, all game state is fine, but when i try to using EZGUI, in a console log is loaded EZGUI , no error but it's seem callback in load theme is not working, how to make it work ?

regards.

**Comment by thesunlover** [comment]
Hello, SLekk.
you'd better provide some example code to get started ;)

regards,
Isko

**Comment by ghost** [comment]
Hello thesunlover, this is my app.js in electron-boilerplate, this file is contains Phaser engine

> var os = require('os');
> var app = require('remote').require('app');
> var jetpack = require('fs-jetpack').cwd(app.getAppPath());
> 
> var PhaserConf = {
>     width: window.innerWidth,
>     height: window.innerHeight,
>     renderer: Phaser.AUTO,
>     parent: 'game',
>     transparent: false,
>     antialias: true,
>     state: this,
>     scaleMode: Phaser.ScaleManager.EXACT_FIT
> };
> 
> var guiContainer;
> var guiObj = {
>     id: 'myWindow',
>     component: 'Window',
>     padding: 4,
>     position: { x: 10, y: 10 },
>     width: 500,
>     height: 500
> };
> 
> window.onload = function () {
> 
> ```
> window.game = new Phaser.Game(PhaserConf);
> 
> // Game GUI
> //Set EZGUI renderer
> EZGUI.renderer = game.renderer;
> 
> //  Add the States your game has.
> window.game.state.add('Boot', GameStates.Boot);
> window.game.state.add('Preloader', GameStates.Preloader);
> window.game.state.add('SplashScreen', GameStates.SplashScreen);
> 
> // GameScenes
> window.game.state.add('Login', GameStates.Login);
> window.game.state.add('Game', GameStates.Game);
> 
> //  Now start the Boot state.
> window.game.state.start('Boot');
> 
> 
> //load EZGUI themes
> //here you can pass multiple themes
> EZGUI.Theme.load(['./assets/kenney-theme/kenney-theme.json'], function (s) {
>     alert('work');
>     var guiContainer = EZGUI.create(guiObj, 'kenney');
> });
> ```
> 
> };

**Comment by ghost** [comment]
now i know why not work with electron, it's cause crossOrigin, electron will load html as file://path/to/file
and ezgui will need http://path.to.file

**Comment by thesunlover** [comment]
ok, good for you.
you can close the issue ;)
Edit:
ups, sorry for inpoliteness: I kindly advise to close the issue.

**Comment by rfox90** [comment]
Actually this needs some changes. We need to detect if we're running inside electron and handle the xmlhttp requests slightly differently. I'll probably throw a PR at your at some point.

**Comment by alaa-eddine** [comment]
fixed thanks to @rfox90 PR (https://github.com/Ezelia/EZGUI/pull/32)
