### ISSUE TITLE
phaser 2.4.6 compatibility

### ISSUE THREAD

**Issue by kerphi** [Ezelia/EZGUI#39]
First of all thank your for this great work on ezgui ! This is one of the best GUI working well with phaser.

But as ezgui is not compatible with phaser 2.4.4 and upper 
any idea to make it compatible with new phaser versions ?

**Comment by alaa-eddine** [comment]
Hi,

Phaser 2.4.4 is supposed to be compatible, but I didn't tried with 2.4.6  .
can you confirm that you are using the compatibility .js  (phaser-compat-2.4.js) ?

please refer to this example for Phaser 2.4 compatibility : https://github.com/Ezelia/EZGUI/blob/master/examples/Phaser/phaser-2.4.html

**Comment by kerphi** [comment]
yes it's working but there is isues :( cf
https://github.com/Ezelia/EZGUI#phaser-244-known-issues

**Comment by alaa-eddine** [comment]
this issue was actually in phaser side and was fixed.
I just forgot to update the readme :) I need to remove it.
the issue in question was that texts was not correctly positionned inside buttons.

did you encountered any issue while using phaser 2.4 ?

**Comment by kerphi** [comment]
honestly i just didn't tested again, I waited for the readme to be updated.
I'm happy to listen this is fixed. I will test soon with a uptodate phaser and I will give your feedback.

**Comment by kerphi** [comment]
Here is my feedback: i tested with phaser 2.4.6 with the phaser-compat-2.4.js and it worked like a charm !
