### ISSUE TITLE
Mousewheel scroll list?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#45]
Maybe I just missed it somewhere but is there a way to programmatically scroll a list?

**Comment by alaa-eddine** [comment]
it's not supported or planed feature since EZGUI mainly targets mobile devices.
but it can implemented by listening to the mousewheel event and moving the scroller container :)

PS. if the game only targets desktop it's better to use DOM IMO, it have a more complete API and UI plugins.

**Comment by Shadowstep33** [comment]
The game will target mobile and browser, with mobile taking precedent. Moving a container is definitely a suitable solution for me; all I should have to do is move the position of the list element itself?

**Comment by alaa-eddine** [comment]
you'll need to move the scroll container :)

if you check this example, I have a horizontal scroll list called hlist1.

to move the elements programmatically by 10px to the left I use this code

```
EZGUI.components.hlist1.container.position.x -= 10;

```

**Comment by Shadowstep33** [comment]
cool makes sense thanks
