### ISSUE TITLE
Layout width control?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#46]
What controls the width/height of a grid column/row? For example, I am setting a list to [3,2] but there is too much vertical spacing between the two rows. Is there a way I can custom define col and row size?

**Comment by Shadowstep33** [comment]
Ofc, the rule of posting kicked in: 

It turns out my list element was the size of my container. Spacing was therefore correct. To clarify: the (perceived) extra vertical height was because the list was taller than I meant for it to be (my own mistake).

**Comment by Shadowstep33** [comment]
I also mis-titled this question, as I was referring to height

**Comment by Shadowstep33** [comment]
I don't want to re-open a new issue and this mostly falls within the same domain:

is there a way to specify a width (or height) of a layout? For example, could I say layout: [%3,2] to say show 3 elements per row and 2 rows? How do I go about setting width of a list, but allowing overflow while maintaining the same amount of elements on screen?

**Comment by alaa-eddine** [comment]
Hi @Shadowstep33   when you define a layout as [3,2] you are actually defining 3 rows and 2 lines.

the layout do not specify a size, it only defines an position, so if the positionned element have a hardcoded width and height which are greater than the layout cell, it will overflow it by default.

**Comment by Shadowstep33** [comment]
Okay makes sense, if I define [3,2] and the each element has a width > listWidth/3 then it will overflow; how would I make an infinite number of columns where three elements appear at a time? [null,2] with each element.width = listWidth/3? Will listWidth increase as I add more elements or will it remain fixed at whatever I define it as?

**Comment by alaa-eddine** [comment]
I don't see what you are trying to do, this syntax : [null,2]  was made available for Lists (which are scrollable), it can have wired behaviour if you use it with normal layout.

if you need to have more elements than what the control size support, you can use List control. the list will be scrollable to allow access to hidden items.
