### ISSUE TITLE
Label component and image?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#48]
Image doesnt appear for the following element:

```
                                    {
                                        id: 'feed-bar-empty',
                                        image: 'feed_bar_empty.png',
                                        component: 'Label',
                                        position: {x: 0, y: 0},
                                        wH: wH,
                                        wW: wW
                                    }
```

though if I change the component to Layout the image appears. Bug or intentional?

**Comment by alaa-eddine** [comment]
Label do not show images, it's a fast control to show text, so use it only when you want to render text.
if you want to display an image you can simply use a 'Window' and put your text in 'text' property :)
