### ISSUE TITLE
Suggestions for filtering lists?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#49]
If I have a list of elements that can be separated by an object property, do you have a reliable or suggested way of handling showing filtered result sets? The way that seems obvious is on click, iterate list and hide/show based on clicked filter. Seems like there should be a more integrated or comprehensive/robust way to do this (for example, examine http://nytimes.github.io/pourover/ for an example of an amazingly solid, robust, and performant filtering library)

**Comment by alaa-eddine** [comment]
unfortunately there is not "robust" solution to do it with EZGUI :) 
the example you showed uses DOM which already have a rich API allowing to implement almost every GUI feature.
EZGUI is far from being that rich, I hope so but it'll require huge work :D 
you can do it by hidding items or by regenerating the template and recreating the list, it all depend on the number of elements, target devices, and code complexity.

**Comment by Shadowstep33** [comment]
Pourover is at heart programmatic in list filtering and result sets with a post filter function that runs/does the templating. Maybe at some point later down the road I'll try to make them work together. 

Sounds like for now I have to just do it like that, thanks!
