### ISSUE TITLE
Line wrap?

### ISSUE THREAD

**Issue by Shadowstep33** [Ezelia/EZGUI#53]
Hi, is there text wrap? I would like to set the width to a static amount and any "overflow" be dropped to the next line.

Also, I hope the method and content of my issue opening is alright. Some of my questions are essentially answers that could be found in docs so I am of the opinion this will help someone write more docs and/or will help others who start using EZGUI and check github's issue tracking for it

**Comment by Shadowstep33** [comment]
Along these lines, is there a text-align property?

**Comment by alaa-eddine** [comment]
Hi, in one of the latest updates I mapped some Pixi.text properties directly to EZGUI text properties.
the word wrap is tested and working, but not sure about the align
take a look at Pixi.Text documentation here : https://pixijs.github.io/docs/PIXI.Text.html

use wordWrap and wordWrapWith to configure the text width.

normally, all Pixi.Text properties can be used, but I didn't tested them all, so try the align, if it don't work I'll check what's going on :)

and yes, the resolved issues can help others, and also will help me or some contributor to write documentation on topics which are not cleare.

for now the documentation is very basic unfortunately, but I try to illustrate every stable feature in examples.

**Comment by Shadowstep33** [comment]
Ooo cool I didn't realize that the text object inherist Pixi's properties. Thanks! I guess I should have realized that lol

And I know it's hard and time consuming to write docs, so no worries man. You're responsive so that's all that matters at end of the day: there is a way to have questions answered! Closing this for now, will mention if align works or not

**Comment by Shadowstep33** [comment]
Just jotting this down here for later reference and will update this comment as I test more:

Inherited properties that don't work:

- stroke
- strokeThickness
