### ISSUE TITLE
Layout manager

### ISSUE THREAD

**Issue by lukejagodzinski** [Ezelia/EZGUI#8]
Hi, the library is a nice tool for creating UIs in PIXI but it lacks one very important feature - Layout Manger. Take a look how it's implemented in Java https://docs.oracle.com/javase/tutorial/uiswing/layout/visual.html

Child elements of component should be layout in the process of creating component but in the process of laying out. Thanks to that you could dynamically add new child to the component (for instance window) and lay out all child elements to fit window properly. Thanks to that you would be also able to resize window and reposition elements.

**Comment by alaa-eddine** [comment]
the issue with such layout handling is that you can't define them using json without nested children :)
if you can give me an example of json syntax to define such layout: https://docs.oracle.com/javase/tutorial/figures/uiswing/layout/BorderLayoutDemo.png I'll be glad to support it :)

other features you mentioned are planed and will come in future releases.
adding children programmatically is already supported throught addChild() and addChildAt() functions, they are not documented because there are some unfixed bugs here.

a visual GUI editor (as a separate project) is also planed but at a later step. 
the main goal now is to get the core features stable and cover most games use cases .

**Comment by lukejagodzinski** [comment]
Of course it's possible :)

``` js
var wnd1 = {
  component: 'Window',
  layout: {
    type: 'Border'
  },
  children: {
    top: {
      component: 'Button'
    },
    right: {
      component: 'Button'
    }
    /* ... */
  }
};

var wnd2 = {
  component: 'Window',
  layout: {
    type: 'Box',
    rows: 2,
    cols: 2
  },
  children: [{
    component: 'Button'
  }, {
    component: 'Button'
  }]
};

var wnd3 = {
  component: 'Window',
  layout: {
    type: 'Linear',
    direction: 'vertical'
  },
  children: [{
    component: 'Button'
  }, {
    component: 'Button'
  }]
};
```

`children` attribute can be treated differently regarding the used layout. Internally it could use `array` instead of `object`.

**Comment by alaa-eddine** [comment]
Well I see what you mean now.
Actually, this will break the generic component model, I need to keep children in an array to be able to sort them, this garantee the display order of Pixi.

your suggestion can be made in what I call "game kits", those will be special components for very specific needs.

for example here is a Game Home screen kit : http://ezgui.ezelia.com/examples/kits/MainScreen-Pixi.html 

the real children structure is hidden, We can use the same logic to create layout kits derived from the layout component while hidding the real children structure.

I'll add it to my todo list, but to be honest it'll not be the priority for next updates, as some important components are still lacking, and bugs need to be fixed.

**Comment by lukejagodzinski** [comment]
Ok, I understand.

I've just tried to make scrollable list but without success. Right now, I have to provide layout grid at the stage of component creation.

I'm writing article about your library for Tizen Developers website.

**Comment by alaa-eddine** [comment]
Thank you a lot for the article ! this will help for sure.

if you show me the code of your scrollable list I can help you :) 
are you trying to make a list like the one used in the app demo ? http://ezgui.ezelia.com/examples/app/pixi.html

**Comment by alaa-eddine** [comment]
about the programmatically child adding, can you please try with addChildAt() function and tell me if it work as expected for you ?

**Comment by lukejagodzinski** [comment]
No problem :-). For now I've just wrote article about basics. In the future when all the features are ready I will write another article. My friend will be creating next article describing example use in the game.

**Comment by alaa-eddine** [comment]
great ! 
please let me know when the article is published :)

**Comment by lukejagodzinski** [comment]
Ok :)
